services:
  web:
    container_name: php
    userns: keep-id
    build:
      context: app_php
      target: builder
      dockerfile: Dockerfile.dev
    environment:
      CI_ENVIRONMENT: ${ENVIRONMENT}
      "databse.default.hostname": "mysql"
      "databse.default.username": ${DB_USER}
      "databse.default.password": ${DB_PASSWORD}
      "databse.default.database": ${DB_DATABASE}
    volumes:
      - ../src:/var/www/html:Z
    ports:
      - '8080:8080'
    depends_on:
        - mysql
  mysql:
    container_name: mysql
    image: docker.io/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
  phpmyadmin:
      image: docker.io/phpmyadmin/phpmyadmin:5.2.1
      platform: linux/amd64
      container_name: phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_USER: ${DB_USER}
        PMA_PASSWORD: ${DB_PASSWORD}
        UPLOAD_LIMIT: 20M
      ports:
        - 8082:80
      depends_on:
        - mysql
